//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateLessonMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrivateLessonMS.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Evaluate.
        /// </summary>
        public static string CanNotEvaluate {
            get {
                return ResourceManager.GetString("CanNotEvaluate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date already receirved by another student.
        /// </summary>
        public static string DateAlreadyReceirved {
            get {
                return ResourceManager.GetString("DateAlreadyReceirved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sended Successfully.
        /// </summary>
        public static string EmailSendSuccessfully {
            get {
                return ResourceManager.GetString("EmailSendSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email used before , please try another one .
        /// </summary>
        public static string EmailUsedBefore {
            get {
                return ResourceManager.GetString("EmailUsedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter activated code sended to your phone.
        /// </summary>
        public static string EnterActivatedCode {
            get {
                return ResourceManager.GetString("EnterActivatedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Service Request.
        /// </summary>
        public static string EnterServiceRequest {
            get {
                return ResourceManager.GetString("EnterServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Student Data.
        /// </summary>
        public static string EnterStudentData {
            get {
                return ResourceManager.GetString("EnterStudentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Teacher Data.
        /// </summary>
        public static string EnterTeacherData {
            get {
                return ResourceManager.GetString("EnterTeacherData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occure.
        /// </summary>
        public static string ErrorOccure {
            get {
                return ResourceManager.GetString("ErrorOccure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Sended Successfully.
        /// </summary>
        public static string EvaluationSendedSuccessfully {
            get {
                return ResourceManager.GetString("EvaluationSendedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InActive User.
        /// </summary>
        public static string InActiveUser {
            get {
                return ResourceManager.GetString("InActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Activated Code.
        /// </summary>
        public static string IncorrectActivatedCode {
            get {
                return ResourceManager.GetString("IncorrectActivatedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Insert Correct Data.
        /// </summary>
        public static string IncorrectData {
            get {
                return ResourceManager.GetString("IncorrectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect File.
        /// </summary>
        public static string IncorrectFile {
            get {
                return ResourceManager.GetString("IncorrectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this user is locked , please contact with adminstration.
        /// </summary>
        public static string LockedUser {
            get {
                return ResourceManager.GetString("LockedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Absher.
        /// </summary>
        public static string NeedAbsher {
            get {
                return ResourceManager.GetString("NeedAbsher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Update Profile.
        /// </summary>
        public static string NeedUpdateProfile {
            get {
                return ResourceManager.GetString("NeedUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Contact Mail Found, please contact with adminstration.
        /// </summary>
        public static string NoContactMailFound {
            get {
                return ResourceManager.GetString("NoContactMailFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No course found.
        /// </summary>
        public static string NoCourseFound {
            get {
                return ResourceManager.GetString("NoCourseFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not activated teacher , please contact with adminstration.
        /// </summary>
        public static string NotActivatedTeacher {
            get {
                return ResourceManager.GetString("NotActivatedTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Not Authrized.
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found Teacher.
        /// </summary>
        public static string NotFoundTeacher {
            get {
                return ResourceManager.GetString("NotFoundTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is not registered.
        /// </summary>
        public static string NotRegisterUser {
            get {
                return ResourceManager.GetString("NotRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed Successfully.
        /// </summary>
        public static string PasswordChangeSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangeSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Error.
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password at least 6 letters.
        /// </summary>
        public static string PasswordFormat {
            get {
                return ResourceManager.GetString("PasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Confirmed.
        /// </summary>
        public static string PhoneConfirmed {
            get {
                return ResourceManager.GetString("PhoneConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone used before , please try another one .
        /// </summary>
        public static string PhoneUsedBefore {
            get {
                return ResourceManager.GetString("PhoneUsedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Sended Successfully.
        /// </summary>
        public static string RequestSendedSuccessfully {
            get {
                return ResourceManager.GetString("RequestSendedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully.
        /// </summary>
        public static string SavedSuccessfully {
            get {
                return ResourceManager.GetString("SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sended to your mail .Please Check Your Mail..
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Accepted.
        /// </summary>
        public static string ServiceAccepted {
            get {
                return ResourceManager.GetString("ServiceAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Refused.
        /// </summary>
        public static string ServiceRefused {
            get {
                return ResourceManager.GetString("ServiceRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student not found.
        /// </summary>
        public static string StudentNotFound {
            get {
                return ResourceManager.GetString("StudentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName or Password Error.
        /// </summary>
        public static string UserNamePasswordError {
            get {
                return ResourceManager.GetString("UserNamePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User used before , please try another name.
        /// </summary>
        public static string UserUsedBefore {
            get {
                return ResourceManager.GetString("UserUsedBefore", resourceCulture);
            }
        }
    }
}
